spring:
  application:
    name: wangjun-post-service

  profiles:
    active: dev

  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:38.76.188.242:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:jianjiange}
      config:
        enabled: true
        namespace: ${NACOS_NAMESPACE:wangjun-dating-dev}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
      discovery:
        enabled: true
        namespace: ${NACOS_NAMESPACE:wangjun-dating-dev}
        group: ${NACOS_GROUP:DEFAULT_GROUP}

server:
  port: ${SERVER_PORT:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - optional:nacos:wangjun-post-service-dev.yml
