package site.jianjiange.postservice.exception;

/**
 * Post 服务业务错误码，供 service 层和后续 gRPC 层统一识别失败原因。
 */
public enum PostErrorCode {

    INVALID_ARGUMENT,
    IDEMPOTENT_CONFLICT,
    POST_NOT_FOUND,
    POST_NOT_PUBLISHED,
    POST_FORBIDDEN,
    LIKE_TEMPORARILY_UNAVAILABLE,
    IMAGE_LIMIT_EXCEEDED,
    IMAGE_NOT_FOUND,
    IMAGE_FORBIDDEN,
    IMAGE_STATUS_INVALID,
    IMAGE_NOT_UPLOADED,
    IMAGE_CONTENT_TYPE_INVALID,
    MINIO_OPERATION_FAILED
}
